/* Generated by WHOI Cable Notebook Designer 1.0.0 */
Problem Description
    title = "Southland Front, 30 m: LD-1 low drag buoy, 40 m polypro"
    type = surface

Analysis Parameters
    static-relaxation = 0.1
    static-iterations = 20000
    static-tolerance = 0.001
    relax-adapt-up = 1.02
    relax-adapt-down = 1.1
    static-outer-iterations = 1000
    static-initial-guess = catenary
    static-solution = relaxation
    static-outer-relaxation = 0.98
    static-outer-tolerance = 0.01
    duration = 210
    ramp-time = 16
    time-step = 0.005
    dynamic-relaxation = 1
    dynamic-iterations = 15
    dynamic-tolerance = 1e-06

Environment
    depth = 30
    rho = 1027
    gravity = 9.81
    x-wind = 5
    bottom-stiffness = 100
    bottom-damping = 1
    forcing-method = morison
    input-type = regular
    x-current = (0, 0.15) (30, 0.15)
    x-wave = (1, 12, 0)

Materials
    "chain_8mm"
        EA = 24000000
        EI = 10
        GJ = 0.1
        m = 1.4
        wet = 11.9
        d = 0.031
        Cdt = 0.01
        Cdn = 0.5
        Cmt = 1.1
        Cmn = 2
        comment = "8 mm chain, approximate"
    "polypro_12mm"
        EA = 120000
        EI = 0.1
        GJ = 0.1
        m = 0.068
        wet = -0.086
        d = 0.012
        Cdt = 0.01
        Cdn = 1.5
        Cmt = 1.1
        Cmn = 2
        comment = "12 mm 3-strand polypropylene, floats, approximate"

Buoys
    "ld1"
        type = axisymmetric
        diameters = (0, 0.05) (0.1, 0.218) (0.38, 0.218) (0.483, 0.1)
        m = 1.1
        Cdn = 0.8
        Cdt = 0.8
        Cdw = 1

Anchors
    "clump"
        color = "red"

Layout
    terminal = {
        anchor = "clump"
    }
    segment = {
        length = 3
        material = "chain_8mm"
        nodes = (7, 1.0)
    }
    segment = {
        length = 40
        material = "polypro_12mm"
        nodes = (41, 1.0)
    }
    terminal = {
        buoy = "ld1"
    }

End
